applyFilterIngforUse <- function(data,name){
  
  if(name == "tenecteplase") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("tenecteplase")) 
  } else if(name == "alteplase") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("alteplase")) 
  } else if(name == "sarilumab") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("sarilumab")) 
  } else if(name == "verteporfin") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("verteporfin")) 
  } else if(name == "tocilizumab") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("tocilizumab")) 
  } else if(name == "varenicline") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("varenicline")) 
  } else if(name == "ceftolozane") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("ceftolozane","ceftozolane_tazobactam")) 
  } else if(name == "tazobactam") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("piperacillin_tazobactam","ceftozolane_tazobactam")) 
  } else if(name == "C1 esterase inhibitor") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("c_1_esterase_inhibitor")) 
  } else if(name == "arsenic trioxide") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("arsenic_trioxide")) 
  } else if(name == "belatacept") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("belatacept")) 
  } else if(name == "ganirelix") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("ganirelix")) 
  } else if(name == "tigecycline") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("tigecycline")) 
  } else if(name == "imiglucerase") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("imiglucerase")) 
  } else if(name == "agalsidase beta") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("agalsidase_beta")) 
  } else if(name == "azithromycin") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("azithromycin")) 
  } else if(name == "clarithromycin") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("clarithromycin")) 
  } else if(name == "penicillin V") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("penicillin V")) 
  } else if(name == "penicillin G") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("penicillin G")) 
  } else if(name == "amoxicillin") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("amoxicillin","amoxicillin_clavulanate")) 
  } else if(name == "clavulanate") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("amoxicillin_clavulanate")) 
  } else if(name == "ceftriaxone") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("ceftriaxone")) 
  } else if(name == "cefotaxime") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("cefotaxime")) 
  } else if(name == "meropenem") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("meropenem")) 
  } else if(name == "cefuroxime") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("cefuroxime")) 
  } else if(name == "piperacillin") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("piperacillin","piperacillin_tazobactam")) 
  } else if(name == "streptokinase") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("streptokinase")) 
  } else if(name == "urokinase") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("urokinase")) 
  } else if(name == "abatacept") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("abatacept")) 
  } else if(name == "tofacitinib") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("tofacitinib")) 
  } else if(name == "baricitinib") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("baricitinib")) 
  } else if(name == "upadacitinib") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("upadacitinib")) 
  } else if(name == "etanercept") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("etanercept")) 
  } else if(name == "infliximab") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("infliximab")) 
  } else if(name == "certolizumab pegol") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("certolizumab")) 
  } else if(name == "CERTOLIZUMAB") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("certolizumab")) 
  } else if(name == "golimumab") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("golimumab")) 
  } else if(name == "anakinra") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("anakinra")) 
  } else if(name == "ranibizumab") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("ranibizumab")) 
  } else if(name == "bevacizumab") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("bevacizumab")) 
  } else if(name == "nicotine") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("nicotine")) 
  } else if(name == "icatibant") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("icatibant")) 
  } else if(name == "ecallantide") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("ecallantide")) 
  } else if(name == "Conestat alfa") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("conestat_alfa")) 
  } else if(name == "lanadelumab") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("lanadelumab")) 
  } else if(name == "berotralstat") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("berotralstat")) 
  } else if(name == "cytarabine") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("cytarabine_liposomal","cytarabine_any","cytarabine_daunorubicin")) 
  } else if(name == "Cytarabine liposomal") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("cytarabine_liposomal","cytarabine_any","cytarabine_daunorubicin")) 
  } else if(name == "CYTARABINE 5'-PHOSPHATE") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("cytarabine_liposomal","cytarabine_any","cytarabine_daunorubicin")) 
  } else if(name == "daunorubicin") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("daunorubicin","cytarabine_daunorubicin")) 
  } else if(name == "idarubicin") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("idarubicin")) 
  } else if(name == "tretinoin") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("tretinoin_oral")) 
  } else if(name == "mycophenolic acid") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("mycophenolic_acid")) 
  } else if(name == "sirolimus") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("sirolimus")) 
  } else if(name == "cyclosporine") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("cyclosporine")) 
  } else if(name == "tacrolimus") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("tacrolimus_no_topical")) 
  } else if(name == "cetrorelix") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("cetrorelix")) 
  } else if(name == "velaglucerase alfa") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("velaglucerase_alfa")) 
  } else if(name == "taliglucerase alfa") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("taliglucerase_alfa")) 
  } else if(name == "Agalsidase alfa") {filtered_data <- data %>% filter(outcome_cohort_name %in% c("agalsidase_alfa")) 
  }
return(filtered_data)
}

